- hosts: all
  gather_facts: yes

  handlers:
    - name: Reload ZSH
      ansible.builtin.command:
        cmd: exec zsh
      changed_when: true

  tasks:

    - name: Download git-prompt.sh
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
        dest: "{{ ansible_user_dir }}/.git-prompt.sh"
      tags:
        - git

    - name: Setup .zshrc template
      ansible.builtin.template:
        src: zshrc.j2
        dest: "{{ ansible_user_dir }}/.zshrc"
      notify: Reload ZSH 
      tags:
        - zsh

    - name: Ensure HTTP pie directory exist
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/httpie/"
        state: directory
      tags:
        - templates

    - name: Setup httpie template
      ansible.builtin.template:
        src: httpie_config.json.j2
        dest: "{{ ansible_user_dir }}/.config/httpie/config.json"
      tags:
        - templates

    - name: Install system pacman packages
      pacman:
        name: "{{ pacman_packages }}"
        state: present
      tags:
        - packages
        - system

    - name: Install pip3 packages
      pip:
        name: "{{ pip_packages }}"
      tags:
        - packages
        - pip

    - name: Perform system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - upgrade
